### ISSUE TITLE
How to bind view model if the json response is a dict

### ISSUE THREAD

**Issue by kodekarim** [JussiSuojanen/friends#3]
hi @JussiSuojanen 
i was going through friends project and its great to see how you have used bindable to connect view and viewmodel

and i have implemented in my project but got stuck to bind view model with dict
your help would be really helpful . Thank you :)
[link to stackoverflow](
https://stackoverflow.com/questions/54613132/how-to-assign-dictionary-struct-to-bindable-type-from-json-data)

**Comment by JussiSuojanen** [comment]
Hi @abdulKarim002,

Great that you like the project and that it has helped you. 

Could you explain a bit more what are trying to do? Do you have a view model which has a dictionary variable? Or do you want to insert your view model into a dictionary? I don't really get the problem from the code that you linked.

**Comment by kodekarim** [comment]
I was trying to assign my viewmodel to my data model which holds the json response
as per your project reference i have successfully implemented in array json response  but i was not able to assign in dictionary  <br>

if you can have a look on the following project file 
file name -  CaseDetailsVM.swift
function name -  getSmallCaseList(id:String)

project link - https://drive.google.com/file/d/16q3ehHuZaoATp2FCpo7k2UOd9JYA-2im/view?usp=sharing

can you help me solve this. :)

**Comment by JussiSuojanen** [comment]
Actually, you have already converted the JSON response to CaseDetailsViewModel in the AppServerClient, so the type that you are receiving in your getSmallCaseList function is already CaseDetailsViewModel, not a Dictionary. 

In case the view will present multiple cells you should just use the Bindable and set an array of CaseDeatilsViewCellType in it. Not sure what your goal is but since the enumeration  CaseDeatilsViewCellType is defined, it looks like you are preparing to present different types of cells. 

If you are presenting the data in a view after the downloading of data is completed you can define the view model like this:

`let caseDetailsCardCell = Bindable<YourTypeHere?>(nil)`

Then replace the nil value after you receive it.

As said, I don't know what the goal is but I hope this points you to right direction :)

**Comment by kodekarim** [comment]
@JussiSuojanen  Thank you
its helped a lot . 👍
