### ISSUE TITLE
how to implement search functionality in your project.

### ISSUE THREAD

**Issue by kkukkadapua** [JussiSuojanen/friends#5]
share the code

**Comment by JussiSuojanen** [comment]
This is not an Issue so I am closing this one. I am quite busy with other projects so I am not doing this for a while. As I replied in my blog here is some pointers how to get started:

Add a searchbar to the tableview. Then implement the callback methods, in the viewcontroller, that get’s called when ever searchbar input changes. When user types in a new character call a
‘sortData(input: String)’ function in the view model from the delegate method. Inside it filter the array that holds your tableview data with the input the user typed. Since the Array is bindlable the table view content is automatically updated after sorting. (If the project setup is the same as in friends project)

I hope this helps! :)
